# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('test_rcpp_hello_world', PACKAGE = 'test')
}

return_given_value <-function(value) {
    .Call('test_return_given_value',value ,PACKAGE = 'test')

}

add_lists <-function(vec1, vec2) {
    .Call('test_add_lists', vec1, vec2, PACKAGE = 'test')
}
