// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <vector>

using namespace Rcpp;

List rcpp_hello_world();
int return_given_value(int value);
std::vector<int> add_lists(std::vector<int> vec1, std::vector<int> vec2);

// rcpp_hello_world
RcppExport SEXP test_rcpp_hello_world() {
    BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
    END_RCPP
}

// example showing how to paese a number(in this case int)
RcppExport SEXP test_return_given_value(SEXP value) {
    BEGIN_RCPP
    int a = Rcpp::as<int>(value);
    Rcpp::RNGScope __rngScope;
    int __result = return_given_value(a);
    return Rcpp::wrap(__result);
    END_RCPP
}

// example showing how to parse a vector of ints
RcppExport SEXP test_add_lists(SEXP vec1, SEXP vec2) {
    BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result =
        add_lists(Rcpp::as<std::vector<int>>(vec1), Rcpp::as<std::vector<int>>(vec2));
    return Rcpp::wrap(__result);
    END_RCPP
}
